# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import demo_pb2 as demo__pb2


class DemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Select = channel.unary_unary(
                '/demo.code.Demo/Select',
                request_serializer=demo__pb2.DemoRequest.SerializeToString,
                response_deserializer=demo__pb2.DemoResponse.FromString,
                )
        self.Insert = channel.unary_unary(
                '/demo.code.Demo/Insert',
                request_serializer=demo__pb2.DemoRequest.SerializeToString,
                response_deserializer=demo__pb2.DemoResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/demo.code.Demo/Update',
                request_serializer=demo__pb2.DemoRequest.SerializeToString,
                response_deserializer=demo__pb2.DemoResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/demo.code.Demo/Delete',
                request_serializer=demo__pb2.DemoRequest.SerializeToString,
                response_deserializer=demo__pb2.DemoResponse.FromString,
                )


class DemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=demo__pb2.DemoRequest.FromString,
                    response_serializer=demo__pb2.DemoResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=demo__pb2.DemoRequest.FromString,
                    response_serializer=demo__pb2.DemoResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=demo__pb2.DemoRequest.FromString,
                    response_serializer=demo__pb2.DemoResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=demo__pb2.DemoRequest.FromString,
                    response_serializer=demo__pb2.DemoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.code.Demo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Demo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.code.Demo/Select',
            demo__pb2.DemoRequest.SerializeToString,
            demo__pb2.DemoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.code.Demo/Insert',
            demo__pb2.DemoRequest.SerializeToString,
            demo__pb2.DemoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.code.Demo/Update',
            demo__pb2.DemoRequest.SerializeToString,
            demo__pb2.DemoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.code.Demo/Delete',
            demo__pb2.DemoRequest.SerializeToString,
            demo__pb2.DemoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
