from scipy import constants

print("constants.zepto =", constants.zepto)
print("constants.atto =", constants.atto)
print("constants.femto =", constants.femto)
print("constants.pico =", constants.pico)
print("constants.nano =", constants.nano)
print("constants.micro =", constants.micro)
print("constants.milli =", constants.milli)
print("constants.centi =", constants.centi)
print("constants.deci =", constants.deci)
print("constants.deka =", constants.deka)
print("constants.hecto =", constants.hecto)
print("constants.kilo =", constants.kilo)
print("constants.mega =", constants.mega)
print("constants.giga =", constants.giga)
print("constants.tera =", constants.tera)
print("constants.peta =", constants.peta)
print("constants.exa =", constants.exa)
print("constants.zetta =", constants.zetta)
print("constants.yotta =", constants.yotta)
